kind: Service
apiVersion: v1
metadata:
  name: csi-intel-rsd-attacher
  labels:
    app: csi-intel-rsd-attacher
spec:
  selector:
    app: csi-intel-rsd-attacher
  ports:
    - port: 20000

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-intel-rsd-attacher
spec:
  serviceName: "csi-intel-rsd-attacher"
  replicas: 1
  selector:
    matchLabels:
      app: csi-intel-rsd-attacher
  template:
    metadata:
      labels:
        app: csi-intel-rsd-attacher
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-intel-rsd-driver
            topologyKey: kubernetes.io/hostname
      serviceAccountName: csi-attacher
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.0.1
          imagePullPolicy: Always
          args:
            - --v=5
            - --csi-address=$(ADDRESS)
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
          - mountPath: /csi
            name: socket-dir

      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-intel-rsd
            type: DirectoryOrCreate
          name: socket-dir
