kind: Service
apiVersion: v1
metadata:
  name: csi-intel-rsd-provisioner
  labels:
    app: csi-intel-rsd-provisioner
spec:
  selector:
    app: csi-intel-rsd-provisioner
  ports:
    - port: 20000

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-intel-rsd-provisioner
spec:
  serviceName: "csi-intel-rsd-provisioner"
  replicas: 1
  selector:
    matchLabels:
      app: csi-intel-rsd-provisioner
  template:
    metadata:
      labels:
        app: csi-intel-rsd-provisioner
    spec:
      serviceAccountName: csi-provisioner
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.0.1
          args:
            - "--provisioner=csi-rsd.intel.com"
            - "--csi-address=$(ADDRESS)"
            - "--connection-timeout=15s"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-intel-rsd
            type: DirectoryOrCreate
          name: socket-dir
