apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-intel-rsd-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-intel-rsd-sc # defined in csi-setup.yaml
